version: "3"
services:
  book_wish_list:
    container_name: book_wish_list
    image: endere/book_wish_list:latest
    ports: 
      - "5678:5678"
    environment:
      - DATABASE_URL=$DATABASE_URL
      - DATABASE_DB=$DATABASE_DB
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - PORT=$PORT
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - ./:/app
